import "./globals.css";
import type { Metadata } from "next";
import { roboto, inter } from "@/lib/fonts";
import { ToastContainer } from "react-toastify";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import { fetchSettings } from "@/lib/apiCalls/PublicApiCalls";

export const metadata: Metadata = {
  title: "Car Store",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {

  // fetchSettings();

  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} antialiased`}
      >
        <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
            />

          <main className="overflow-hidden">
            <Header />
            <div className="mt-[67px]">
              {children}
            </div>
            <Footer />
          </main>
      </body>
    </html>
  );
}
