import "./globals.css";
import type { Metadata } from "next";
import { roboto, inter } from "@/lib/fonts";
import { ToastContainer } from "react-toastify";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
// import { useUserStore } from "@/app/stores/useUserStore";
// import { fetchUser } from "@/lib/apiCalls/authApiCalls";
// import { ProfileInfoApiResponse } from "@/lib/Dto";
import { cookies } from "next/headers";
// import axios from "axios";
export const metadata: Metadata = {
  title: "Car Store",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {

  const token = (await cookies()).get('token')?.value;
  if (token) {
    // console.log(token)
    // const res = await fetchUser(token) as ProfileInfoApiResponse;
    // if (res.errorMessage)
    //   console.log(res.errorMessage);
    
    // console.log(res.data)
    // const res = await axios.get('http://rentacar.somee.com/api/Account/GetProfile',
    //   {
    //     headers: {
    //       Authorization: `Bearer ${token}`,
          
    //     },
    //     withCredentials: true
    //   }
    // );
    // console.log(res.statusText)
    // console.log(res.status)
    // console.log(res.data)
  }
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} antialiased`}
      >
        <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
            />
          <main className="overflow-hidden">
            <Header />
            <div className="mt-[67px]">
              {children}
            </div>
            <Footer />
          </main>
      </body>
    </html>
  );
}
