
import SidebarAdmin from "@/components/sections/SidebarAdmin";
import type { Metadata } from "next";
// import { profileLinks } from "@/lib/utils";
// import { getProfileInfo } from "@/lib/apiCalls/authApiCalls";
// import { ProfileInfoApiResponse } from "@/lib/Dto";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {


    const token = (await cookies()).get('token')?.value
    
    if (!token)
        redirect('/')
    
    return (
        <main className="overflow-hidden min-h-screen p-7">
            <section className="container mx-auto">
                <div className="grid grid-cols-1 lg:grid-cols-6 gap-5 items-stretch">
                    <SidebarAdmin 
                        classes="lg:col-span-2" 
                        name={'Mahmoud Abu Lail'}
                        email={'mahmoud@gmail.com'}
                        img={'/images/services.jpg'}
                    />
                    <div className="lg:col-span-4 shadow-type1 bg-white rounded-3xl p-5 md:p-7">
                        {children}
                    </div>
                </div>
            </section>
        </main>
    );
}
