
import Sidebar from "@/components/sections/Sidebar";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "User Profile",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}
export const dynamic = 'force-dynamic'
export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {

    const token = (await cookies()).get('token')?.value
    const isAdmin = (await cookies()).get('isAdmin')?.value
    
    if (!token || isAdmin === 'true') 
        redirect('/')
    
    return (
        <main className="overflow-hidden min-h-screen p-7">
            <section className="container mx-auto">
                <div className="grid grid-cols-1 lg:grid-cols-6 gap-5 items-stretch">
                    <Sidebar 
                        role="user"
                        classes="lg:col-span-2" 
                    />
                    <div className="lg:col-span-4 shadow-type1 bg-white rounded-3xl p-5 md:p-7">
                        {children}
                    </div>
                </div>
            </section>
        </main>
    );
}
